/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package car;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gokul
 */
public class Addcar extends javax.swing.JFrame {

    /**
     * Creates new form Addcar
     */
    public Addcar() {
        initComponents();
        autocarID();
    }
    Connection con;
    PreparedStatement pst;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtregno = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        comboCartype = new javax.swing.JComboBox<>();
        txtbrand = new javax.swing.JTextField();
        txtmodel = new javax.swing.JTextField();
        comboFuel = new javax.swing.JComboBox<>();
        jRadioButtonAuto = new javax.swing.JRadioButton();
        jRadioButtonManual = new javax.swing.JRadioButton();
        txtmyear = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        comboAvail = new javax.swing.JComboBox<>();
        submitButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtcarid = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtregid = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AddCar");

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car/alert.png"))); // NOI18N
        jLabel1.setText("                    IMPORTANT NOTE: During the COVID-19 pandemic, our all cars have been sterilized for your health.");
        jLabel1.setToolTipText("");
        jLabel1.setOpaque(true);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setText("New Car Registration");
        jLabel2.setToolTipText("");

        txtregno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        jLabel3.setText("Car Type");
        txtregno.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 135, 33));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        jLabel4.setText("Brand");
        jLabel4.setToolTipText("");
        txtregno.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 140, 30));

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        jLabel5.setText("Model");
        txtregno.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 135, 27));

        jLabel6.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        jLabel6.setText("Fuel Type");
        txtregno.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 135, 50));

        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        jLabel7.setText("Gear Type");
        jLabel7.setToolTipText("");
        txtregno.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 135, 27));

        jLabel8.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        jLabel8.setText("Model Year");
        txtregno.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 135, 27));

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        jLabel9.setText("Price/Day");
        txtregno.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 105, 28));

        jLabel10.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        jLabel10.setText("Availability");
        jLabel10.setToolTipText("");
        txtregno.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 135, 36));

        comboCartype.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        comboCartype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hatchbag", "Sedan", "SUV" }));
        comboCartype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCartypeActionPerformed(evt);
            }
        });
        txtregno.add(comboCartype, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 135, 30));
        txtregno.add(txtbrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 135, 30));
        txtregno.add(txtmodel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 135, 31));

        comboFuel.setFont(new java.awt.Font("Microsoft JhengHei", 0, 13)); // NOI18N
        comboFuel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Petrol", "Diesel", "EV" }));
        txtregno.add(comboFuel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 135, 31));

        jRadioButtonAuto.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jRadioButtonAuto.setText("Automatic");
        jRadioButtonAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonAutoActionPerformed(evt);
            }
        });
        txtregno.add(jRadioButtonAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 93, -1));

        jRadioButtonManual.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jRadioButtonManual.setText("Manual");
        jRadioButtonManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonManualActionPerformed(evt);
            }
        });
        txtregno.add(jRadioButtonManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 93, -1));

        txtmyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmyearActionPerformed(evt);
            }
        });
        txtregno.add(txtmyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 135, 33));

        txtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceActionPerformed(evt);
            }
        });
        txtregno.add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 140, 28));

        comboAvail.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        comboAvail.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        comboAvail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAvailActionPerformed(evt);
            }
        });
        txtregno.add(comboAvail, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, 135, 30));

        submitButton.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        submitButton.setText("Submit Request");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        txtregno.add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 550, 144, 31));

        cancelButton.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        txtregno.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 550, 128, 30));

        jLabel12.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        jLabel12.setText("Car ID");
        txtregno.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 140, 30));
        txtregno.add(txtcarid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 140, 30));

        jLabel13.setFont(new java.awt.Font("Microsoft JhengHei", 1, 13)); // NOI18N
        jLabel13.setText("Car Reg.no");
        txtregno.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 120, 30));

        txtregid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtregidActionPerformed(evt);
            }
        });
        txtregno.add(txtregid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 140, 30));

        jLabel11.setBackground(new java.awt.Color(255, 204, 204));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car/loginBackground.png"))); // NOI18N
        jLabel11.setOpaque(true);
        txtregno.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 610));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(txtregno, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtregno, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 891, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmyearActionPerformed

    private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriceActionPerformed

    private void comboAvailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAvailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAvailActionPerformed

    private void comboCartypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCartypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCartypeActionPerformed

    private void jRadioButtonAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonAutoActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonAuto.isSelected()) {
            jRadioButtonManual.setEnabled(false);
        } else {
            jRadioButtonManual.setEnabled(true);
        }

    }//GEN-LAST:event_jRadioButtonAutoActionPerformed
    public void autocarID()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/cardb", "root","");
            Statement s=con.createStatement();
            ResultSet rs=s.executeQuery("select Max(car_id) from cars");
            rs.next();
            rs.getString("Max(car_id)");
            if(rs.getString("Max(car_id)")== null)
            {
                txtcarid.setText("A0001");
            }
            else
            {
                long id=Long.parseLong(rs.getString("Max(car_id)").substring(2,rs.getString("Max(car_id)").length()));
                id++;
                txtcarid.setText("A0" + String.format("%03d",id));
            }
            
        } 
        catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Addcar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    public void Refresh(){
        txtcarid.setText("");
        txtbrand.setText("");
        txtmodel.setText("");
        txtmyear.setText("");
        txtprice.setText("");
        jRadioButtonAuto.setVisible(true);
        jRadioButtonManual.setVisible(true);
        txtregid.setText("");
        
    }
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        String carid = txtcarid.getText();
        String cartype = comboCartype.getSelectedItem().toString();
        String brand = txtbrand.getText();
        String model = txtmodel.getText();
        String fuel = comboFuel.getSelectedItem().toString();
        String myear = txtmyear.getText();
        String cost = txtprice.getText();
        String avail=comboAvail.getSelectedItem().toString();
        String cregid=txtregid.getText();
        String gearType = "";
        if (jRadioButtonAuto.isSelected()) {
            gearType = "Automatic";
        }
        if (jRadioButtonManual.isSelected()) {
            gearType = "Manual";
        }
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/cardb", "root", "");
            pst = con.prepareStatement("insert into caraddrequest (car_id,car_type,brand,model,fuel_type,gear_type,model_year,price,available,car_regnum)values(?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1,carid);
            pst.setString(2,cartype);
            pst.setString(3,brand);
            pst.setString(4,model);
            pst.setString(5,fuel);
            pst.setString(6,gearType);
            pst.setString(7,myear);
            pst.setString(8,cost);
            pst.setString(9,avail);
            pst.setString(10,cregid);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Request sent to Admin ....");
            Refresh();
        } 
        catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Addcar.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_submitButtonActionPerformed

    private void jRadioButtonManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonManualActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonManual.isSelected()) {
            jRadioButtonAuto.setEnabled(false);
        } else {
            jRadioButtonAuto.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButtonManualActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void txtregidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtregidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtregidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addcar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addcar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addcar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addcar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addcar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> comboAvail;
    private javax.swing.JComboBox<String> comboCartype;
    private javax.swing.JComboBox<String> comboFuel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonAuto;
    private javax.swing.JRadioButton jRadioButtonManual;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField txtbrand;
    private javax.swing.JTextField txtcarid;
    private javax.swing.JTextField txtmodel;
    private javax.swing.JTextField txtmyear;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtregid;
    private javax.swing.JPanel txtregno;
    // End of variables declaration//GEN-END:variables
}
