/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package car;

import com.toedter.calendar.JDateChooser;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;

/**
 *
 * @author gokul
 */
public class RentalForm extends javax.swing.JFrame {

    private Border border;

    /**
     * Creates new form RentalForm
     */
    public RentalForm() {
        initComponents();
        LoadCustid();
        LoadCarsid();
        Date date = new Date();
        jTextFieldPickupDate.setMinSelectableDate(date);
        jTextFieldPickupDate.setDateFormatString("dd/MM/yyyy");
        jTextFieldReturnDate.setDateFormatString("dd/MM/yyyy");
        jTextFieldReturnDate.setMinSelectableDate(date);
    }
    Connection con;
    PreparedStatement pst, pst1;

    public void refresh() {
        txtbrand.setText("");
        txtmodel.setText("");
        txtavail.setText("");
    }

    public void LoadCustid() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/cardb", "root", "");
            pst = con.prepareStatement("select *from customer");
            ResultSet rs = pst.executeQuery();
            comboCustID.removeAllItems();
            while (rs.next()) {
                comboCustID.addItem(rs.getString(2));
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(RentalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void LoadCarsid() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/cardb", "root", "");
            pst = con.prepareStatement("select *from cars where available = 'Yes'");
            ResultSet rs = pst.executeQuery();
            ComboCarID.removeAllItems();
      
         
            while (rs.next()) {
                ComboCarID.addItem(rs.getString(2));
            } 
//            else {
//                JOptionPane.showMessageDialog(this, "No cars available for rent");
//                refresh();
//            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(RentalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelCustomerInfo = new javax.swing.JLabel();
        jLabelCustomerID = new javax.swing.JLabel();
        comboCustID = new javax.swing.JComboBox<>();
        jLabelName = new javax.swing.JLabel();
        txtcustname = new javax.swing.JTextField();
        jLabelSurname = new javax.swing.JLabel();
        txtproofid = new javax.swing.JTextField();
        jLabelPhone = new javax.swing.JLabel();
        txtphone = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabelCarInfo = new javax.swing.JLabel();
        jLabelCarID = new javax.swing.JLabel();
        ComboCarID = new javax.swing.JComboBox<>();
        jLabelBrand = new javax.swing.JLabel();
        txtbrand = new javax.swing.JTextField();
        jLabelModel = new javax.swing.JLabel();
        txtmodel = new javax.swing.JTextField();
        jLabelPickupDate = new javax.swing.JLabel();
        jLabelReturnDate = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtavail = new javax.swing.JTextField();
        BookButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        jTextFieldPickupDate = new com.toedter.calendar.JDateChooser();
        jTextFieldReturnDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RentalForm");

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/car/alert.png"))); // NOI18N
        jLabel1.setText("                                          IMPORTANT NOTE: During the COVID-19 pandemic, our all cars have been sterilized for your health.");
        jLabel1.setOpaque(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelCustomerInfo.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabelCustomerInfo.setText("Customer Information");

        jLabelCustomerID.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        jLabelCustomerID.setText("ID Number");

        comboCustID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCustIDActionPerformed(evt);
            }
        });

        jLabelName.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        jLabelName.setText("Name");

        txtcustname.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        txtcustname.setBorder(BorderFactory.createCompoundBorder(border,
            BorderFactory.createEmptyBorder(0, 10, 0, 0)));
    txtcustname.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtcustnameActionPerformed(evt);
        }
    });

    jLabelSurname.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
    jLabelSurname.setText("Proof ID");

    txtproofid.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
    txtproofid.setBorder(BorderFactory.createCompoundBorder(border,
        BorderFactory.createEmptyBorder(0, 10, 0, 0)));
txtproofid.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtproofidActionPerformed(evt);
    }
    });

    jLabelPhone.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
    jLabelPhone.setText("Phone");

    txtphone.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
    txtphone.setBorder(BorderFactory.createCompoundBorder(border,
        BorderFactory.createEmptyBorder(0, 10, 0, 0)));
txtphone.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtphoneActionPerformed(evt);
    }
    });

    jLabelEmail.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
    jLabelEmail.setText("Email Address");

    txtemail.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
    txtemail.setBorder(BorderFactory.createCompoundBorder(border,
        BorderFactory.createEmptyBorder(0, 10, 0, 0)));
txtemail.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtemailActionPerformed(evt);
    }
    });

    jLabelCarInfo.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
    jLabelCarInfo.setText("Car Information");

    jLabelCarID.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
    jLabelCarID.setText("ID Number");

    ComboCarID.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            ComboCarIDActionPerformed(evt);
        }
    });

    jLabelBrand.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
    jLabelBrand.setText("Brand");

    txtbrand.setBorder(BorderFactory.createCompoundBorder(border,
        BorderFactory.createEmptyBorder(0, 10, 0, 0)));
txtbrand.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtbrandActionPerformed(evt);
    }
    });

    jLabelModel.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
    jLabelModel.setText("Model");

    txtmodel.setBorder(BorderFactory.createCompoundBorder(border,
        BorderFactory.createEmptyBorder(0, 10, 0, 0)));
txtmodel.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtmodelActionPerformed(evt);
    }
    });

    jLabelPickupDate.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
    jLabelPickupDate.setText("Pick-up Date *");

    jLabelReturnDate.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
    jLabelReturnDate.setText("Return Date *");

    jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
    jLabel2.setText("Availability**");

    txtavail.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
    txtavail.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            txtavailActionPerformed(evt);
        }
    });

    BookButton.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
    BookButton.setText("Proceed to Book");
    BookButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            BookButtonActionPerformed(evt);
        }
    });

    closeButton.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
    closeButton.setText("close");
    closeButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            closeButtonActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addGap(37, 37, 37)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelCustomerInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCustID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtphone, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcustname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addComponent(jLabelPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(24, 24, 24)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelEmail)
                        .addComponent(txtproofid, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(BookButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(107, 107, 107)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtbrand)
                        .addComponent(jLabelPickupDate)
                        .addComponent(jTextFieldPickupDate, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtmodel)
                        .addComponent(jLabelReturnDate)
                        .addComponent(jTextFieldReturnDate, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(0, 9, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelCarID, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelCarInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(79, 79, 79))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(ComboCarID, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabelModel)
                        .addComponent(txtavail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(closeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(42, 42, 42)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelCustomerInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabelCarInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(27, 27, 27)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabelCarID, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(comboCustID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(ComboCarID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtavail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(56, 56, 56)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabelSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabelBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabelModel))
            .addGap(13, 13, 13)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtcustname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtproofid, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtbrand, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(32, 32, 32)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelPhone)
                .addComponent(jLabelEmail)
                .addComponent(jLabelPickupDate)
                .addComponent(jLabelReturnDate))
            .addGap(18, 18, 18)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(txtphone, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addComponent(txtemail)
                .addComponent(jTextFieldPickupDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldReturnDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(BookButton)
                .addComponent(closeButton))
            .addGap(31, 31, 31))
    );

    txtcustname.setEnabled(false);
    txtproofid.setEnabled(false);
    txtphone.setEnabled(false);
    txtemail.setEnabled(false);
    txtbrand.setEnabled(false);
    txtmodel.setEnabled(false);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(32, 32, 32)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(58, 58, 58)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(84, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 939, Short.MAX_VALUE)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents
String regno = "";
    private void comboCustIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCustIDActionPerformed
        String custid = comboCustID.getSelectedItem().toString();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/cardb", "root", "");

            pst = con.prepareStatement("select * from customer where cust_id=?");
            pst.setString(1, custid);
            ResultSet rs = pst.executeQuery();
            if (rs.next() == false) {
                JOptionPane.showMessageDialog(this, "cust ID Not found");
            } else {

                txtcustname.setText(rs.getString(3));
                txtproofid.setText(rs.getString(5));
                txtphone.setText(rs.getString(8));
                txtemail.setText(rs.getString(9));
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(RentalForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_comboCustIDActionPerformed

    private void ComboCarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCarIDActionPerformed
        String carid = ComboCarID.getSelectedItem().toString();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/cardb", "root", "");

            pst = con.prepareStatement("select * from cars where car_id=?");
            pst.setString(1, carid);
            ResultSet rs = pst.executeQuery();
            if (rs.next() == false) {
                JOptionPane.showMessageDialog(this, "car ID Not found");
            } else {
                String avail = rs.getString("available");
                txtavail.setText(avail);
                if (avail.equals("Yes")) {
                    txtbrand.setText(rs.getString(4));
                    txtmodel.setText(rs.getString(5));
                    regno = rs.getString(11);
                } else {
                    txtbrand.setText("");
                    txtmodel.setText("");

                }
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(RentalForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ComboCarIDActionPerformed

    private void txtcustnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcustnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcustnameActionPerformed

    private void txtavailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtavailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtavailActionPerformed

    private void txtproofidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproofidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtproofidActionPerformed

    private void txtbrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbrandActionPerformed

    private void txtmodelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmodelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmodelActionPerformed

    private void txtphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphoneActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void BookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookButtonActionPerformed
        // TODO add your handling code here:
        String custid = comboCustID.getSelectedItem().toString();
        String carid = ComboCarID.getSelectedItem().toString();
        String custname = txtcustname.getText();

        String pone = txtphone.getText();
        SimpleDateFormat Date_Format = new SimpleDateFormat("dd/MM/yyyy");
        String date = Date_Format.format(jTextFieldPickupDate.getDate());
        int cost = 0;
        SimpleDateFormat Date_Format1 = new SimpleDateFormat("dd/MM/yyyy");
        String due = Date_Format1.format(jTextFieldReturnDate.getDate());
        Date date1 = jTextFieldPickupDate.getDate();
        Date date2 = jTextFieldReturnDate.getDate();
        long differenceInMilliseconds = date2.getTime() - date1.getTime();
        int differenceInDays = (int) differenceInMilliseconds / (1000 * 60 * 60 * 24);
        //  System.out.print("Days : "+differenceInDays+"Phone : "+pone);
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/cardb", "root", "");
            pst = con.prepareStatement("select price from cars where car_id=?");
            pst.setString(1, carid);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                cost = rs.getInt("price");
            }
            int rentcost = cost * differenceInDays;
            try {
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/cardb", "root", "");
                pst = con.prepareStatement("insert into rentedcars(cust_id,cust_name,cust_phone,car_id,car_regno,pick_date,return_date,rent_price)values(?,?,?,?,?,?,?,?)");
                pst.setString(1, custid);
                pst.setString(2, custname);
                pst.setString(3, pone);
                pst.setString(4, carid);
                pst.setString(5, regno);
                pst.setString(6, date);
                pst.setString(7, due);
                pst.setInt(8, rentcost);
                pst.executeUpdate();
                pst1 = con.prepareStatement("update cars set available='No' where car_id=?");
                pst1.setString(1, carid);
                pst1.executeUpdate();
                JOptionPane.showMessageDialog(this, "Rent successfull");
                jTextFieldPickupDate.setDate(null);
                jTextFieldReturnDate.setDate(null);
               // LoadCarsid();
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(RentalForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(RentalForm.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_BookButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentalForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookButton;
    private javax.swing.JComboBox<String> ComboCarID;
    private javax.swing.JButton closeButton;
    private javax.swing.JComboBox<String> comboCustID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBrand;
    private javax.swing.JLabel jLabelCarID;
    private javax.swing.JLabel jLabelCarInfo;
    private javax.swing.JLabel jLabelCustomerID;
    private javax.swing.JLabel jLabelCustomerInfo;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelModel;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPhone;
    private javax.swing.JLabel jLabelPickupDate;
    private javax.swing.JLabel jLabelReturnDate;
    private javax.swing.JLabel jLabelSurname;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.toedter.calendar.JDateChooser jTextFieldPickupDate;
    private com.toedter.calendar.JDateChooser jTextFieldReturnDate;
    private javax.swing.JTextField txtavail;
    private javax.swing.JTextField txtbrand;
    private javax.swing.JTextField txtcustname;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtmodel;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtproofid;
    // End of variables declaration//GEN-END:variables
}
